#!/bin/bash

FILE=`which toilet`
if [ -f "$FILE" ]; then
    toilet --gay GinLab
else
    echo "apt get install toilet"
fi

#
# Cluster
#
# https://atmospherejs.com/meteorhacks/cluster
# You can use your existing MONGO_URL for this
#export CLUSTER_DISCOVERY_URL=mongodb://host:port/db,
# this is the direct URL to your server (it could be a private URL)
#export CLUSTER_ENDPOINT_URL=http://ipaddress
# mark your server as a web service (you can set any name for this)
#export CLUSTER_SERVICE=web

#export MONGO_URL=mongodb://localhost:27017/GinLab
#export MAIL_URL=yourAdminEmailAddress
meteor --no-lint --no-release-check #--port 3333
